import { db } from '../server/db.js';
import { AuthFlowError, createUser, requestAuthCode, verifyAuthCode } from '../server/auth.js';

const unique = Date.now().toString();
const email = `auth-${unique}@synau.local`;
const username = `auth${unique.slice(-10)}`;
let lastConsoleCode = '';
const originalInfo = console.info;
console.info = (...args: unknown[]) => {
  const line = args.join(' ');
  const match = line.match(/code=(\d{6})/);
  if (match) lastConsoleCode = match[1];
  originalInfo(...args);
};

try {
  const signupChallenge = await requestAuthCode({
    mode: 'sign_up',
    firstName: 'Auth',
    lastName: 'Tester',
    username,
    email,
  });
  if (!signupChallenge.challengeId || !lastConsoleCode) throw new Error('Sign-up code was not generated by the development email transport.');
  const signup = verifyAuthCode({ challengeId: signupChallenge.challengeId, code: lastConsoleCode });
  if (!signup.created || signup.user.username !== username) throw new Error('Sign-up verification did not create the expected user.');

  lastConsoleCode = '';
  const signInChallenge = await requestAuthCode({ mode: 'sign_in', identifier: username });
  if (!lastConsoleCode) throw new Error('Sign-in code was not generated by the development email transport.');
  const signIn = verifyAuthCode({ challengeId: signInChallenge.challengeId, code: lastConsoleCode });
  if (signIn.created || signIn.user.email !== email) throw new Error('Username sign-in did not resolve the created user.');

  let oneTimeRejected = false;
  try {
    verifyAuthCode({ challengeId: signInChallenge.challengeId, code: lastConsoleCode });
  } catch (error) {
    oneTimeRejected = error instanceof AuthFlowError && error.code === 'auth_code_invalid';
  }
  if (!oneTimeRejected) throw new Error('A verified code was accepted more than once.');

  createUser({ email: 'demo@synau.local', firstName: 'Demo', lastName: 'Learner', username: 'demo' });
  const demoChallenge = await requestAuthCode({ mode: 'sign_in', identifier: 'demo' });
  const demo = verifyAuthCode({ challengeId: demoChallenge.challengeId, code: '020599' });
  if (demo.user.email !== 'demo@synau.local') throw new Error('Demo verification code did not authenticate the demo user.');

  console.log(JSON.stringify({ ok: true, assertions: [
    'signup-fields-and-code',
    'username-sign-in',
    'verification-code-is-single-use',
    'demo-code-020599',
  ] }, null, 2));
} finally {
  console.info = originalInfo;
  db.close();
}
